import { Component, defineElement, FC, RenderFunction } from './component';
import { adoptStyles, css, scopeCSS, unsafeCSS } from './css';
import {
    createHook,
    getCurrentElement,
    getCurrentElementPhase,
    onDidLoad,
    onDidUnload,
    onUpdated,
    useBindMethod,
    useComputed,
    useElement,
    useElements,
    useEvent,
    useListen,
    useProp,
    useReactive,
    useRef,
    useStyles,
    useWatch,
} from './hooks';
import { queueMicrotaskPolyfill } from './polyfills';

export {
    defineElement,
    RenderFunction,
    useRef,
    useProp,
    scopeCSS,
    adoptStyles,
    unsafeCSS,
    css,
    Component,
    onDidLoad,
    onDidUnload,
    onUpdated,
    useBindMethod,
    useElement,
    useElements,
    useStyles,
    useEvent,
    useListen,
    createHook,
    getCurrentElement,
    getCurrentElementPhase,
    queueMicrotaskPolyfill,
    FC,
    useReactive,
    useWatch,
    useComputed,
};
